sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '0.10'
  - '4'
before_install:
  - npm i -g npm@lts
before_script:
  - npm prune
after_success:
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"